import js from "@eslint/js";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  // index.d.ts, fixtures/fake-llmux.d.ts, test/sidecar.test.d.ts, and
  // index.js are published build artifacts (generated by `tsc`), not
  // hand-written source — they must never be linted, edited, or deleted.
  globalIgnores(["node_modules", "**/*.d.ts", "index.js", "fixtures/*.js", "test/*.js"]),
  // llmux's Node SDK is plain TS, no framework. Type-aware rules are enabled
  // (parserOptions.projectService) specifically so no-floating-promises and
  // the no-unsafe-* family actually run — untyped linting is what let a
  // 220-error TS migration pass green elsewhere in the fleet.
  {
    files: ["index.ts", "fixtures/**/*.ts", "test/**/*.ts"],
    extends: [js.configs.recommended, ...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
]);
