import js from "@eslint/js";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  // index.d.ts, fixtures/fake-llmux.d.ts, test/sidecar.test.d.ts, and
  // index.js are published build artifacts (generated by `tsc`), not
  // hand-written source — they must never be linted, edited, or deleted.
  globalIgnores(["node_modules", "**/*.d.ts", "index.js", "direct.js", "fixtures/*.js", "test/*.js"]),
  // llmux's Node SDK is plain TS, no framework. Type-aware rules are enabled
  // (parserOptions.projectService) specifically so no-floating-promises and
  // the no-unsafe-* family actually run — untyped linting is what let a
  // 220-error TS migration pass green elsewhere in the fleet.
  {
    files: ["index.ts", "direct.ts", "fixtures/**/*.ts", "test/**/*.ts", "examples/**/*.ts"],
    extends: [js.configs.recommended, ...tseslint.configs.strictTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  // examples/fake-upstream.mjs is deliberately plain JS, not TS: all three
  // JS-runtime SDKs (node, deno, bun) spawn that same fixture verbatim, and
  // `node:http` is the one HTTP server API all three implement. Without this
  // block it would be enumerated by `eslint .` with zero rules applied — the
  // same silent-zero-coverage shape the scripts/*.mjs block below exists for.
  {
    files: ["examples/**/*.mjs"],
    extends: [js.configs.recommended],
    languageOptions: {
      globals: { console: "readonly", process: "readonly", setTimeout: "readonly" },
      sourceType: "module",
    },
  },
  // check-lint-config.mjs is ".mjs", matched by no `files` glob above (which
  // only covers index.ts/fixtures/test *.ts) — it was enumerated in
  // `eslint .`'s file count but had zero rules applied to it (confirmed via
  // --print-config showing 0 resolved rules, and an injected unused-var
  // probe that went unflagged before this block existed). It runs under
  // Node only. `globals` isn't a dependency here, so its only two ambient
  // identifiers (console, process) are declared directly rather than
  // pulling in a new package for a two-name list.
  {
    files: ["scripts/check-lint-config.mjs"],
    extends: [js.configs.recommended],
    languageOptions: {
      globals: { console: "readonly", process: "readonly" },
      sourceType: "module",
    },
  },
]);
